name: Wake Up App

on:
  schedule:
    # Runs every 6 hours (Streamlit sleeps after 12)
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |

          curl -I https://melodian-records.streamlit.app/
